[neut]

number_of_events = 100 # the number of probe interactions to simulate

verbosity = "very_quiet"

rng_seed = "file" #Reads random number from a file so all events are the same 

output_format = "neutroot"
# output_format = "NuHepMC"

simulation_mode = "neutrino" # This option includes electron scattering

[neut.vertex]

position_type = "origin" # place the vertex at [0.0, 0.0, 0.0]

[neut.probe]

species = "numu"
throwinke = "false"

#direction_type = "z" # probe approaches target along [0.0, 0.0, 1.0]

direction_type = "fixed" # probe approaches target along vector specified by direction
direction = [0.0, 0.0,1.0] # same as "z"

energy_spectrum_type = "root"
energy_histogram = [ "/<path_to_directory>/t2kflux_2016_plus250kA.root", "enu_nd280_numu", "gev"]

#energy_spectrum_type = "fixed"
#energy_mev = 235.5

[neut.target]

num_nucleons = 12
num_bound_protons = 6
num_free_protons = 0

[neut.target.nuclear_effects]

fermi_motion = "on"
pauli_blocking = "on"
pauli_blocking_2p2h = "on"

formation_length = "on_except_qe"
formation_zone_scat_parameter = 0.08

[neut.target.hadron_FSI]

model =  "incl" # options are "none",""default", "incl-hybrid" (which runs incl when compatible, and standard if not) and "incl"
#if running with default, nucleon_cascade and pion_cascade parameters are used from the default card file.
# if running with INCL, INCL parameters (to be implemented) will be used.
# if running with hybrid, all parameters will be used based off CCQE interaction model. 

deexcitation = "abla"

[neut.target.hadron_FSI.nucleon_cascade] # this is only for classic NEUT cascade

nucleon_rescattering = "on"

[neut.target.hadron_FSI.pion_cascade] # this is only for classic NEUT cascade

pion_rescattering = "on"


[neut.interaction_model]

mode_choice_type = "rescaled" 

[neut.interaction_model.mode_rescaling] # turn these on as and when new channels are needed

"CC_QE_nu" = 1.0
"CC_2p2h_nu" = 0.0
"CC_RES_ppi+_nu" = 0.0
"CC_RES_ppi0_nu" = 0.0
"CC_RES_npi+_nu" = 0.0
"CC_COH_nu" = 0.0
"CC_DIF_nu" = 0.0
"CC_eta_nu" = 0.0
"CC_kaon_nu" = 0.0
"CC_1gamma_nu" = 0.0
"CC_multi_pi_nu" = 0.0
"CC_DIS_nu" = 0.0

"NC_elastic_free_p_nu" = 0.0
"NC_elastic_bound_p_nu" = 0.0
"NC_elastic_n_nu" = 0.0
"NC_RES_npi0_nu" = 0.0
"NC_RES_ppi0_nu" = 0.0
"NC_RES_ppi-_nu" = 0.0
"NC_RES_npi+_nu" = 0.0
"NC_COH_nu" = 0.0
"NC_DIF_nu" = 0.0
"NC_eta_n_nu" = 0.0
"NC_eta_p_nu" = 0.0
"NC_kaon_n_nu" = 0.0
"NC_kaon_p_nu" = 0.0
"NC_multi_pi_nu" = 0.0
"NC_1gamma_n_nu" = 0.0
"NC_1gamma_p_nu" = 0.0
"NC_DIS_nu" = 0.0

"CC_QE_free_proton_nubar" = 0.0
"CC_QE_bound_proton_nubar" = 0.0
"CC_2p2h_nubar" = 0.0
"CC_RES_npi-_nubar" = 0.0
"CC_RES_ppi0_nubar" = 0.0
"CC_RES_ppi-_nubar" = 0.0
"CC_COH_nubar" = 0.0
"CC_DIF_nubar" = 0.0
"CC_eta_nubar" = 0.0
"CC_kaon_nubar" = 0.0
"CC_1gamma_nubar" = 0.0
"CC_multi_pi_nubar" = 0.0
"CC_DIS_nubar" = 0.0

"NC_elastic_free_p_nubar" = 0.0
"NC_elastic_bound_p_nubar" = 0.0
"NC_elastic_n_nubar" = 0.0
"NC_RES_npi0_nubar" = 0.0
"NC_RES_ppi0_nubar" = 0.0
"NC_RES_ppi-_nubar" = 0.0
"NC_RES_npi+_nubar" = 0.0
"NC_COH_nubar" = 0.0
"NC_DIF_nubar" = 0.0
"NC_eta_n_nubar" = 0.0
"NC_eta_p_nubar" = 0.0
"NC_kaon_n_nubar" = 0.0
"NC_kaon_p_nubar" = 0.0
"NC_1gamma_n_nubar" = 0.0
"NC_1gamma_p_nubar" = 0.0
"NC_multi_pi_nubar" = 0.0
"NC_DIS_nubar" = 0.0

[neut.interaction_model.radiative_corrections]

model = "off"
gamma_attach_fraction = 0.1
egamma_low_threshold = 10
gamma_angular_distribution = "exp_decay"
# gamma_angular_distribution = "isotropic"

[neut.interaction_model.electron]

q2_threshold_MeV = 10000
coulomb = { enabled = "on", use_ema = "off" }
q3_dependent_eb = { enabled = "off", gradient = 0, intercept = 0 }

[neut.interaction_model.QE]

#model = "nieves" # use SF model by ueno-mori for NC (unrecommend)
#model = "nieves_furmanski_abe" # use SF model by frumanski-abe for NC
model = "rome" # Benhar SF
#model = "llewelyn-smith"
#model = "rmf"

#erpa = "on" # incompatible with model = "nieves", use nieves.rpa = "on" instead

kappa = 1.0

second_class_currents_vector_scale = 0.0
second_class_currents_axial_scale = 0.0
pseudo_scalar_scale = 1

pionless_delta_decay = "off"
pionless_delta_decay_fraction = 0.0

[neut.interaction_model.QE.rmf]
# Nuclear potential for the RDIWA model. By default ED-RMF is used.
potential = "edrmf"

# If an event has a missing energy above the src_Emiss_cut, then it 
# will be an SRC event and produce an extra nucleon.
src_Emiss_cut = 80

[neut.interaction_model.QE.rome] # this is the setting that should be used

# Shift SF inputs along the separation energy axis
separation_energy_shift_gev = 0

# Behavior if chosen separation energy for event is unphysical
separation_energy_negative_behavior = "pin_to_0"
# separation_energy_negative_behavior = "redraw_from_sf"

maximum_energy = 100
maximum_momentum = 300

strange_axial_coupling = 0.0

#disable if you want the old spectral function
sf_C12_table="2024"
sf_neutron_energy_core="on"

NN_pair_fraction = 0.05

#this sets src boundary to a realistic cutoff shape, with a isospin dependent jailing cut
src_model_type = "nuwro"
src_kinematic_threshold = -1.0


[neut.interaction_model.QE.nieves]

nuclear_model = "lfg"
rpa = "off"

rpa_parameters.fp0in = 0.33
rpa_parameters.fp0ex = 0.45
rpa_parameters.fstar = 2.13
rpa_parameters.af = 1.0
rpa_parameters.pilambda = 1200.0
rpa_parameters.cr0 = 2.0
rpa_parameters.rholambda = 2500
rpa_parameters.gp = 0.63
rpa_parameters.xmpi = 139.57
rpa_parameters.xmrho = 775.4
rpa_parameters.irel = 1.0

binding_energy = "off"
binding_energy_shift = "off"

[neut.interaction_model.QE.vector_form_factors]

cc_form = "BBBA05"
nc_form = "BBBA05"
dipole.vector_mass = 0.84

[neut.interaction_model.QE.axial_form_factors]

form = "dipole"

[neut.interaction_model.QE.axial_form_factors.dipole]

axial_mass = 1.03
nc_axial_mass = 1.21

[neut.interaction_model.2p2h]

#model = "nieves_table"
model = "nieves_hadron_tensor"

#rdependent is needed to be on if you want realistic 2p2h stuff
qval = "zero" #"r-dependent"

use3p3h = false
